---
title: "Instance Theory Typing"
author: "Walter"
date: "June 13, 2018"
output: html_document
---
```{r}
X=10  #we will subtract this amount from random indices to create random letter IKSI vectors
subjects=5
all_performance<-c() 
trials=100
practice=1000 #this describes how many times the X is - & + from random letter RTs
numVectors=100 # this is analagous to the number of traces, mem_retrieval_times
# so in Matt's example mem_retrieval_times are the traces
# in this case each vector of letter RTs are the traces 
```
In the following code, the for each subject,
the first loop creates a trace distribution, that is full of
vectors with random RTs for each letter
the second loop finds the vector that has the least typing time to 
type the word "word"
the minimum total RT is the performance
```{r}
for(i in 1:subjects) 
{
    word="word"
    vectors=data.frame()
    
    # generate dataframe of random letter RTs
    for(j in 1:numVectors)
    { alphabet=rnorm(26,150,0.0001) #single vector of times for each letter 
      for(i in 1:practice)
        { 
        
          regress=as.integer(runif(1,1,26))
          alphabet[regress]=alphabet[regress]+X
          #in case one is a zero
          repeat{
          progress=as.integer(runif(1,1,26))
          if((alphabet[progress]-X)>1E-10)
            break
          }
          alphabet[progress]=alphabet[progress]-X
         
        }
       vectors=rbind(vectors,alphabet)
    }
    memory_retrieval_times = vectors
    performance <- c()
    for(trial in 1:trials){
     # performance[trial] <- min(memory_retrieval_times[1:trial,]) # fastest one always wins
     # gets which letter to type
      letterIndex=c()
      lets=toupper(strsplit(word,"")[[1]])
      for(i in 1:length(lets))
     letterIndex=c( letterIndex, which(  LETTERS == lets[i]))
      # get the vector that produces lowest total letter times for this word
      minimum=4000
      # find the letter RT vector that will type "word" fastest sum of IKSI lowest
      for(i in 1:trial)
         { if(sum(memory_retrieval_times[i,letterIndex])<minimum)
            {minimum=sum(memory_retrieval_times[i,letterIndex])
             bestVector=i
            }
        }
      performance[trial]=minimum
    }
   all_performance=c(all_performance,performance) 
}
```

```{r}

subject_df <- data.frame(subject=rep(1:subjects,each=trials),
                         trial = rep(1:trials,subjects),
                         performance = all_performance)
```